noise: True  # specify if simulation should be run with or without noise
sampling_rate: 5.  # sampling rate in GHz used internally in the simulation.
speedup:
  minimum_weight_cut: 1.e-5
  delta_C_cut: 0.698  # 40 degree
propagation:
  ice_model: southpole_2015
signal:
  model: Alvarez2009
trigger:
  noise_temperature: 300  # in Kelvin
weights:
  weight_mode: core_mantle_crust
output:
  channel_traces: True
  electric_field_traces: False
  sim_channel_traces: True
  sim_electric_field_traces: False
