LDFLAGS= -L${shell root-config --libdir}  -L${RNO_G_DEPS_INSTALL_DIR}/lib -L${RNO_G_INSTALL_DIR}/lib
CXXFLAGS= -I${shell root-config --cflags} -I${RNO_G_DEPS_INSTALL_DIR}/include -I${RNO_G_INSTALL_DIR}/include/
LDLIBS += ${shell root-config --libs} -lmattak
